#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

hours=0
minutes=0
while [ $hours -lt 13 ]
do
    while [ $minutes -lt 60 ]
    do
        echo "$hours:$minutes"
        minutes=$((minutes+1))
    done
    minutes=0
    hours=$((hours+1))
done | head -n 70
